name: Update Version

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

# Add necessary permissions
permissions:
  contents: write
  pull-requests: write

jobs:
  # Run tests first to ensure we don't release with failing tests
  test:
    name: Test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PowerShell on non-Windows platforms
        if: matrix.os != 'windows-latest'
        run: |
          # Display PowerShell version information
          pwsh -c '$PSVersionTable'

      - name: Run tests on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          # Enable script execution
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

          # Run the tests
          ./Run-Tests.ps1

      - name: Run tests on macOS/Linux
        if: matrix.os != 'windows-latest'
        shell: pwsh
        run: |
          # Run the tests
          ./Run-Tests.ps1

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: |
            TestResults/
            */TestResults/
          if-no-files-found: ignore

  update-version:
    needs: test # Only run if tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for changelog generation
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main # Explicitly checkout the main branch

      - name: Extract version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Update PSD1 version
        shell: pwsh
        run: |
          $psd1Path = "./CrackCrestronPassword.psd1"
          $version = "${{ steps.get_version.outputs.VERSION }}"

          Write-Host "Updating version to: $version"
          Write-Host "File exists: $(Test-Path $psd1Path)"

          $content = Get-Content -Path $psd1Path -Raw
          $updatedContent = $content -replace "(ModuleVersion\s*=\s*['`"])[0-9]+\.[0-9]+\.[0-9]+(['`"])", "`${1}$version`$2"
          $updatedContent | Set-Content -Path $psd1Path -NoNewline

          # Verify the update worked
          $newContent = Get-Content -Path $psd1Path -Raw
          Write-Host "Updated content contains version: $($newContent.Contains($version))"

      - name: Generate changelog
        id: github_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-config.json"
          outputFile: "CHANGELOG.md"
          failOnError: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify changelog generation
        run: |
          echo "Changelog output: ${{ steps.github_changelog.outputs.changelog }}"
          echo "Changelog file exists: $(ls -la CHANGELOG.md || echo 'File not found')"
          if [ -f "CHANGELOG.md" ]; then
            echo "Changelog content:"
            cat CHANGELOG.md
          fi

      # Commit the changes back to the repository
      - name: Commit changes back to the repository
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add CrackCrestronPassword.psd1 CHANGELOG.md
          git commit -m "chore: update version to ${{ steps.get_version.outputs.VERSION }} [skip ci]"
          git push origin master  # Explicitly push to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create a release directly from this workflow
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.github_changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: |
            CrackCrestronPassword.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
