name: Update Version

on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  # Run tests first
  test:
    name: Test on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PowerShell on non-Windows platforms
        if: matrix.os != 'windows-latest'
        run: |
          # Display PowerShell version information
          pwsh -c '$PSVersionTable'

      - name: Run tests on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          # Enable script execution
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

          # Run the tests
          ./Run-Tests.ps1

      - name: Run tests on macOS/Linux
        if: matrix.os != 'windows-latest'
        shell: pwsh
        run: |
          # Run the tests
          ./Run-Tests.ps1

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}
          path: |
            TestResults/
            */TestResults/
          if-no-files-found: ignore

  # Only proceed with the version update if tests pass
  update-version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important for changelog generation

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update PSD1 version
        shell: pwsh
        run: |
          $psd1Path = "./CrackCrestronPassword.psd1"
          $version = "${{ steps.get_version.outputs.VERSION }}"

          $content = Get-Content -Path $psd1Path -Raw
          $updatedContent = $content -replace "(ModuleVersion\s*=\s*['`"])[0-9]+\.[0-9]+\.[0-9]+(['`"])", "`${1}$version`$2"
          $updatedContent | Set-Content -Path $psd1Path -NoNewline

          Write-Host "Updated module version to $version"

      - name: Generate changelog
        id: github_changelog
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          configuration: ".github/changelog-config.json"
          outputFile: "CHANGELOG.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create a release directly from this workflow
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.github_changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: |
            CrackCrestronPassword.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
